StackStorm/st2ci

- actions/workflows/setup_st2.yaml
The git clone of st2 repo is approaching close to 60 seconds on more than a few occasions.
> Increase timeout for git clone st2 repo step

- rules/build_pkgs_master_on_pytests.yaml
- rules/st2_pkg_test_unstable_u14.yaml
If the build fails then need to not perform this action maybe perform another action.
> get rules to check status in build pipeline

- actions/workflows/st2_pkg_e2e_test.yaml
If nslookup on hostname fails, use instance ID to destroy the VM.
> Include instance ID in destroy VM step

- rules/st2_pkg_test_unstable_u14.yaml
- rules/st2_pkg_test_unstable_u14_enterprise.yaml
Context from slack:
```
lakstorm [11:10]  
Bah. Circle CI changed their payload. https://gist.github.com/lakshmi-kannan/b49719c89b30eb5858fe676798cabbe0#file-gistfile1-txt-L57
lakstorm [11:11]  
The committer_name is now GitHub :confused:
[11:11]  
I’ll update rule to use author_name instead.
[11:12]  
The problem is there are two paths to trigger e2e tests - A merge to st2packages -> e2e packaging tests or a merge to st2 -> st2-packages build -> e2e
[11:16]  
Here is the payload when there is a merge to st2 https://gist.github.com/lakshmi-kannan/7a7feae1a609c4cdcf13195301addd43#file-gistfile1-txt-L31 (See build_parameters) and here’s a commit to st2-packages https://gist.github.com/lakshmi-kannan/b49719c89b30eb5858fe676798cabbe0#file-gistfile1-txt-L43 (No build_parameters)
```
> Use build_params st2 commit sha if available

- policies/st2_pkg_e2e_tests_retry_on_failure.yaml
This should hopefully help up with intermediate / temporary issues.
It also means actual failure will now be indicated as two consequent workflow failures.
> Retry st2_pkg_e2e_retry_on_failure flow on failure

- actions/workflows/st2_pkg_promote.yaml
- actions/workflows/st2_pkg_promote_enterprise.yaml
It seems like we want to access `result.body` of the HTTP runner.
Here is the action result object:
```
result: 
body:
- created_at: '2016-02-12T16:28:22.000Z'
distro_version: ubuntu/trusty
downloads_count_url: /api/v1/repos/StackStorm/staging-
```
> Fix invalid attribute name when accessing data in the result object.

- actions/workflows/st2_pkg_promote.yaml
- actions/workflows/st2_pkg_promote_enterprise.yaml
This way we pre-filter the result and don't overload Mistral.
> Pass filename_filter param to list_packages actions

- actions/workflows/st2_pkg_promote.yaml
- actions/workflows/st2_pkg_promote_enterprise.yaml
Remove revision check and query packagecloud always to get the package download URL.
> Fix package promotion

- actions/workflows/st2_pkg_e2e_test.yaml
On EL6 the `upgrade_to_enterprise` script was continuing to fail because it would timeout. This change increases the timeout of that script in an attempt to resolve the issue on EL6.
> Increase timeout for upgrade to enterprise script

- policies/retry_st2_pkg_e2e_test_on_failure.yaml
This should hopefully save us some time and reduce the amount of false positives due to intermediate failures we can't directly control (networking issues, etc.).
> Add policy to retry st2_pkg_e2e_test on failure up to 1 time

- actions/workflows/bwc_pkg_promote_all.yaml
https://github.com/StackStorm/st2ci/commit/cd11fb4bf71593506995f950383921c0cb64eed1 removed several published variables in the workflow to promote BWC packages:
- promoted_bwc_ipfabric_suite
- promoted_bwc_ipfabric_packs
- promoted_bwc_topology
- promoted_bwc_cli
However, these vars are still referenced in the final success message sent to slack, and it's causing the workflow to return a "failed" result. This PR removes these vars from the slack message.
> Removed reference to undeclared vars in slack success message

- actions/workflows/mistral.yaml
The number of tests has increased and the timeout needs to accomodate.
> Increase timeout for the test task

- actions/workflows/st2_pkg_upgrade_e2e_test.yaml
https://github.com/StackStorm/st2ci/pull/77 added a task to stop all st2 services before updating stackstorm to the new version. The primarily intention of this was to ensure mistral isn't running on the new version before we can run the database migration tasks later on in the workflow. If you don't do this, you'll see [error messages](https://gist.github.com/Mierdin/08b60819d81761dd631e4e3e8121c2a3) that indicate a table already exists when performing the database migration.
While this worked for community upgrade tests, the enterprise workflow installs the enterprise packages (`st2cd.st2_upgrade_to_enterprise`), and appears to restart all st2 services, which effectively nullifies this services stop task. So, this PR re-orders these tasks so that whether we're testing community, or …
> Moved services stop task so that the enterprise upgrade doesn't restart services

- actions/workflows/st2_pkg_e2e_test.yaml
Event though we're running e2e test with debug flag, the logs it produces are often insufficient to properly diagnose the issue. This task will enable extensive logging before running any e2e tests.
> Enable system-wide debug mode

- actions/workflows/mistral.yaml
- actions/workflows/st2_pkg_upgrade_e2e_test.yaml
At @humblearner request, I will not update the build node once this is merged.
> Updated timeouts to reflect what's currently running on build node

- actions/workflows/st2_pkg_upgrade_deb.yaml
It breaks our upgrade tests when config has changed because existing
config with database credentials will get overwritten with a new empty
config without credentials and as such, upgrade will fail.
> Remove --force-confnew DPKG option

- rules/st2_pkg_e2e_test_centos7_on_st2_pr.yaml
- rules/st2_pkg_e2e_test_ubuntu16_on_st2_pr.yaml
Because of the bug in still fresh CircleCI 2.0 workflows, they include `PR` info for `master` branch, which shouldn't be there and so this triggers a build.
Adding more filters to trigger e2e tests only for PRs in `st2` repo.
> Fix for CircleCI build after st2 PR merge

- actions/st2_pkg_upgrade_deps_el7.sh
For some reason, npm package is not installed on the BWC installation.
> Fix upgrade of dependencies for el7

- actions/workflows/bwc_pkg_promote_all.yaml
- actions/workflows/mistral.yaml
- actions/workflows/st2_pkg_e2e_test.yaml
- actions/workflows/st2_pkg_promote_all.yaml
- actions/workflows/st2_pkg_test_and_promote.yaml
- actions/workflows/st2_pkg_test_and_promote_enterprise.yaml
- actions/workflows/st2_pkg_upgrade_e2e_test.yaml
Use FQDN for `st2cicd` by default to get the best from https://github.com/StackStorm/ops-infra/issues/113 feature.
> Use FQDN for st2cicd

- actions/workflows/st2_pkg_e2e_test.yaml
Without explicit version, going back and doing CI testing patch releases for old versions (N-1, N-2...) will break CI. For example, if current stable version is 2.7.x and we want to ship a patch on 2.6, these changes force enterprise upgrade to 2.6.x. Without explicit version, enterprise upgrades would resort to latest stable enterprise bits and therefore our CI would actually not be testing the 2.6 combo of community + enterprise. 
Related: https://github.com/StackStorm/st2cd/pull/335
> Explicitly pass version to upgrade_to_enterprise script

- actions/st2_pkg_e2e_test.meta.yaml
- actions/workflows/st2_pkg_e2e_test.yaml
Added support for creating and destroying Windows VMs in e2e tests. This also feeds windows credentials along to the actual e2e tests.
> Added Window support to e2e tests

- actions/workflows/bwc_pkg_promote_all.yaml
Version hack no longer needed after https://github.com/StackStorm/st2-enterprise-auth-backend-ldap/pull/47
> Removed st2-auth-ldap version hack

- actions/st2_pkg_e2e_test.meta.yaml
- actions/st2_pkg_upgrade_e2e_test.meta.yaml
That size should be 10% faster than previous c4 one and it's also a bit cheaper.
> Use new c5 instance size for e2e tests

- actions/bwc_pkg_promote_all.meta.yaml
- actions/st2_pkg_promote_all.meta.yaml
We should uncomment that once we decide to start promoting Ubuntu 18.04 packages from staging unstable to other repos.
> Don't try to promote Ubuntu 18 packages

- actions/workflows/st2_pkg_e2e_test.yaml
Somehow the engine is not publishing the variable if using the shorthand.
> Fix publish of failed variable

- actions/workflows/st2_pkg_test_and_promote.yaml
Revert notification channels back to thunderdome. Add core.noop action to promote_all, there may be a bug with no reporting transition errors for actionless task.
> Various fixes to st2_pkg_test_and_promote

- actions/workflows/st2_pkg_test_and_promote.yaml
Remove parallel branches due to bug with overwritten context vars and add logic to skip mistral for ubuntu 18.
> Update task sequence for st2_pkg_test_and_promote

- actions/workflows/mistral.yaml
The vars defined in output may not be assigned if the workflow fails. To avoid errors with referencing unassigned variables, initialize the variables in the vars section.
> Make sure output vars are already assigned

- actions/workflows/bwc_pkg_promote_all.yaml
- actions/workflows/st2_pkg_promote_all.yaml
Due to issue https://github.com/StackStorm/orquesta/issues/112, variables in the context are overwritten on task join. To avoid the issue, refactor the workflow from parallel to sequential.
> Refactor package promotion workflow from parallel to sequential

- rules/st2_pkg_test_and_promote_unstable_el6.yaml
- rules/st2_pkg_test_and_promote_unstable_el6_enterprise.yaml
- rules/st2_pkg_test_and_promote_unstable_el7.yaml
- rules/st2_pkg_test_and_promote_unstable_el7_enterprise.yaml
- rules/st2_pkg_test_and_promote_unstable_u14.yaml
- rules/st2_pkg_test_and_promote_unstable_u14_enterprise.yaml
- rules/st2_pkg_test_and_promote_unstable_u16.yaml
- rules/st2_pkg_test_and_promote_unstable_u16_enterprise.yaml
Per @m4dcoder request, change the build schedule so all builds complete in the morning. With this change, it is easier to perform maintenance and updates on our CI server in the afternoon.
> Complete all builds before noon

- actions/workflows/st2_pkg_e2e_test.yaml
On failure when upgrading to enterprise packages, add a task transition to cleanup.
> Add auto-remediation step to cleanup on upgrade enterprise failure

- rules/st2_pkg_test_and_promote_unstable_el6.yaml
- rules/st2_pkg_test_and_promote_unstable_el6_enterprise.yaml
- rules/st2_pkg_test_and_promote_unstable_el7.yaml
- rules/st2_pkg_test_and_promote_unstable_el7_enterprise.yaml
- rules/st2_pkg_test_and_promote_unstable_u14.yaml
- rules/st2_pkg_test_and_promote_unstable_u14_enterprise.yaml
- rules/st2_pkg_test_and_promote_unstable_u16.yaml
- rules/st2_pkg_test_and_promote_unstable_u16_enterprise.yaml
- rules/st2_pkg_test_and_promote_unstable_u18.yaml
- rules/st2_pkg_test_and_promote_unstable_u18_enterprise.yaml
Change the CI jobs to test and promote unstable packages to 8 AM PST and unstable enterprise packages to 9 AM PST.
> Change the schedule for the daily CI jobs

- actions/st2_pkg_upgrade_deps_el6.sh
CI for RHEL6 enterprise upgrade is failing due to insufficient disk space reported by RabbitMQ.  Add a temporary fix to clear some disk space for the CI to succeed.
> Add a cleanup step to free disk space for el6

- actions/workflows/st2_pkg_e2e_test.yaml
The create VM workflows can fail after the instance is already running in AWS. In this case, we still need the instance ID to destroy the VM on failure. Refactor the create VM workflows to try returning the instance ID.
> Publish VM InstanceId on failure

- actions/st2_pkg_upgrade_e2e_test.meta.yaml
- actions/workflows/st2_pkg_upgrade_e2e_test.yaml
Add chatops option to the e2e test for package upgrade and pass this option to the step that runs the e2e test.
> Add chatops option to the e2e test for upgrade

- actions/st2_pkg_test_and_promote_enterprise.meta.yaml
Add UBUNTU18 in the enum for supported distro for testing and promoting enterprise packages.
> Enable promotion of unstable bionic packages

- rules/st2_pkg_test_unstable_u14_dev.yaml
- rules/st2_pkg_test_unstable_u14_enterprise_dev.yaml
- rules/st2_pkg_test_unstable_u16_dev.yaml
- rules/st2_pkg_test_unstable_u16_enterprise_dev.yaml
- rules/st2_pkg_test_unstable_u18_dev.yaml
- rules/st2_pkg_test_unstable_u18_enterprise_dev.yaml
The circleci build events from the release process does not have a ST2_COMMIT_SHA in the build parameters. The action execution of `st2ci.st2_pkg_e2e_test` being triggered are failing with error `Failed to render parameter "initial_commit"` because `has no attribute 'ST2_COMMIT_SHA'`. The value assignment of the `initial_commit` parameter is changed to the same if else Jinja expression for assigning hostname. If build_parameters are not present, then use the vcs_revision in the payload. Fixes #155
> Fix action trigger for circleci build event rules

- actions/st2_pkg_e2e_test.meta.yaml
- actions/st2_pkg_upgrade_e2e_test.meta.yaml
- actions/workflows/st2_pkg_e2e_test.yaml
- actions/workflows/st2_pkg_upgrade_e2e_test.yaml
Don't pass windows key during CI, use defaults from K/V based on st2cd repo workflows
> Obtain windows private key from st2kv storage

- actions/workflows/st2_pkg_e2e_test.yaml
If version is provided as input to the e2e test, use the given version. If version is not provided to the e2e test, get the version from the installed st2 package. If the installed st2 package is a dev version, leave the version null. Otherwise, use the installed version which will dictate which st2tests branch to install.
> Get st2 version from installed package

- actions/st2_pkg_e2e_test.meta.yaml
- actions/st2_pkg_e2e_test_notify.meta.yaml
- actions/workflows/st2_pkg_e2e_test.yaml
- actions/workflows/st2_pkg_e2e_test_notify.yaml
- actions/workflows/st2_pkg_upgrade_e2e_test.yaml
This PR splits out the `st2tests_version` input parameter from StackStorm/st2cd#427 from the `version` input parameter.
I maintain backwards compatibility with just specifying the `version` parameter by using YAQL's `switch()` function and only using `st2tests_version` if it is defined. I also keep an existing bug with comparing `version` to the string `null`.
And just for clarity, I also tweak the Slack notification workflows to dump the st2tests branch as well.
> Split out st2tests_version from ST2 version

- rules/st2_pkg_test_and_promote_unstable_el8_enterprise.yaml
We don't have enterprise packages for RHEL 8 yet, so this CI run always fails.
Disable until we have enterprise packages built.
> Disable st2_pkg_test_and_promote_unstable_el8_enterprise

- actions/workflows/bwc_pkg_promote_all.yaml
Since StackStorm/orquesta#112 is fixed, we can now run our promote tasks in parallel.
> Promote all of the enterprise packages in parallel

- actions/workflows/bwc_pkg_promote_all.yaml
The internal st2cicd server doesn't run a version of StackStorm that has a version of Orquesta with StackStorm/orquesta#112 applied, so it was premature to promote packages in parallel.
This undoes #169 and reverts commit 96ec939cea430dc7009bd2a15b1c8f45de61dd7f.
The correct time to tweak this back is after 3.2.0 is released and st2cicd is rebuilt to use that release (it is currently running 3.1.0).
> Promote packages in series after all

- rules/st2_pkg_e2e_test_centos8_on_st2_pr.yaml
Fixing an oversight introduced in https://github.com/StackStorm/st2ci/pull/162 which adds CentOS8 e2e check rule to stackstorm/st2 PRs, but used `centos7` distro instead of `centos8`.
That resulted in a wrong distro environment and missing centos8 status reported for Github PR.
Fixed status: ![](https://i.imgur.com/RYYIAaJ.png)
Example: https://github.com/StackStorm/st2/pull/4874
> Fix CentOS8 CI rule for st2 PR github status

- actions/workflows/bwc_pkg_promote_all.yaml
- actions/workflows/mistral.yaml
- actions/workflows/st2_pkg_e2e_test_notify.yaml
- actions/workflows/st2_pkg_promote_all.yaml
- actions/workflows/st2_pkg_test_and_promote.yaml
- actions/workflows/st2_pkg_test_and_promote_enterprise.yaml
- actions/workflows/st2_pkg_upgrade_e2e_test.yaml
Related to https://github.com/StackStorm/st2cd/pull/431
> Use #opstown as alert channel instead of old #stackstorm

- actions/workflows/st2_pkg_upgrade_e2e_test.yaml
The list of packages to install was the same on every version of the os.
With us dropping Mistral support in u18 and el8 we were incorrectly trying to upgraded `st2mistral` on these OSes.
This PR adds a conditional exception for the "legacy" OSes (u16, el6, el7) to install the "legacy" packages which include `st2mistral`.
By default we'll install the "modern" packages on new OSes (u18+, el8+) without Mistral.
I coded it like this so when we add new OSes we do not need to make a new exception, they will install the right packages by default. However, when we remove an OS we can remove the exceptions and clean up the code.
> Fixing package upgrade e2e test for u18 and el8

- actions/workflows/st2_pkg_upgrade_rpm.yaml
During release testing we found a problem where `st2ci.st2_pkg_upgrade_rpm` threw the following error:
```
{
"output": null,
"errors": [
{
"message": "mapping values are not allowed here\n  in \"<string>\", line 15, column 13:\n              do:\n                ^"
}
]
}
```
It looks like there were extra spaces before the `do` clause for el8.
> Fix syntax error in st2_pkg_upgrade_rpm

- actions/st2_pkg_upgrade_deps_el8.sh
The `st2ci/actions/st2_pkg_upgrade_deps_el8.sh` file is not used in `v3.2` release. The `if...fi` loop was commented out incorrectly. 
Fixed.
> removing extra fi

- actions/workflows/st2_pkg_upgrade_e2e_test.yaml
Should fix this:
```
"errors": [
{
"message": "Execution failed. See result for details.",
"type": "error",
"result": {
"10.0.3.120": {
"succeeded": false,
"failed": true,
"return_code": 127,
"stderr": "Failed to stop mistral-api.service: Unit mistral-api.service not loaded.\nFailed to stop mistral-server.service: Unit mistral-server.service not loaded.\n/tmp/5ea7915d3cdb969b55585c07/st2_perform_migrations.sh: line 151: /opt/stackstorm/mistral/bin/mistral-db-manage: No such file or directory",
"stdout": "--> No migrations to run for version 3.2\n############### ERROR ###############\n# Failed on step - Perform updates #\n#####################################"
}
},
"task_id": "migrate_models"
}
]
```
> Skip mistral SQL migrations on modern OSes that don't install Mistral

- rules/st2_pkg_test_and_promote_unstable_el7_enterprise.yaml
- rules/st2_pkg_test_and_promote_unstable_el8_enterprise.yaml
- rules/st2_pkg_test_and_promote_unstable_u16_enterprise.yaml
- rules/st2_pkg_test_and_promote_unstable_u18_enterprise.yaml
- rules/st2_pkg_test_unstable_u16_enterprise.yaml
- rules/st2_pkg_test_unstable_u16_enterprise_dev.yaml
- rules/st2_pkg_test_unstable_u16_enterprise_packaging.yaml
- rules/st2_pkg_test_unstable_u18_enterprise.yaml
- rules/st2_pkg_test_unstable_u18_enterprise_dev.yaml
- rules/st2_pkg_test_unstable_u18_enterprise_packaging.yaml
Extreme Networks is winding down support for enterprise packages. The daily scheduled CI jobs to check enterprise packages will be disabled.
> Disable the daily scheduled jobs for checking enterprise packages

- actions/workflows/install_latest_revision_of_rpm_pkg.yaml
Added `-y` to the `repoquery` command because it was getting stuck being prompted to import a GPG key from PackageCloud when testing out the EL8 upgrade e2e test.
This error was shown in the command output:
```StackStorm_staging-stable                       1.2 kB/s | 833  B     00:00    
StackStorm_staging-stable                        22 kB/s | 3.9 kB     00:00    
Importing GPG key 0x0A38E96F:
Userid     : "https://packagecloud.io/StackStorm/staging-stable (https://packagecloud.io/docs#gpg_signing) <support@packagecloud.io>"
Fingerprint: A7FF A8B7 8DED 1ADC 2CDD A026 B1B9 A6E8 0A38 E96F
From       : https://packagecloud.io/StackStorm/staging-stable/gpgkey
expand
```
When trying to run `yum makecache` the following was displayed:
```
StackStorm_staging-stable                       1.3 …
```
> Added -y to repoquery command so el8 imports GPG keys

- actions/workflows/install_latest_revision_of_rpm_pkg.yaml
This time the package upgrade workflow failed with the following error:
```
StackStorm_staging-stable                       1.3 kB/s | 833  B     00:00    
StackStorm_staging-stable                        23 kB/s | 3.9 kB     00:00    
Importing GPG key 0x0A38E96F:
Userid     : \"https://packagecloud.io/StackStorm/staging-stable (https://packagecloud.io/docs#gpg_signing) <support@packagecloud.io>\"
Fingerprint: A7FF A8B7 8DED 1ADC 2CDD A026 B1B9 A6E8 0A38 E96F
From       : https://packagecloud.io/StackStorm/staging-stable/gpgkey
StackStorm_staging-stable                       1.3 MB/s | 1.2 MB     00:00    
StackStorm_staging-stable-source                1.3 kB/s | 819  B     00:00    
StackStorm_staging-stable-source                 21 kB/s | 3.9 kB     00:00    
Importing GPG key …
```
> Added sudo to repoquery to import AWS RHEL repo SSL cert

- actions/install_latest_revision_of_rpm_pkg.meta.yaml
- actions/workflows/install_latest_revision_of_rpm_pkg.yaml
- actions/workflows/st2_pkg_upgrade_rpm.yaml
Next problem:
RHEL/CentOS 7  doesn't recognize `repoquery -y` as a valid option. I think the "right" fix is to run `yum makecache` before running `repoquery` so that the cache, SSL certificates and GPG keys are all imported (hopefully).
To do this though, we need to run `sudo yum makecache -y` on EL8 and `sudo yum makecache -y fast` on EL7. Unfortunately EL8 doesn't allow the `fast` argument and EL7 takes too long to run plain `makecache`, so i have a switch in there to vary the arguments based on distro.
> Fixing RHEL/CentOS cache creation

- rules/st2_pkg_test_and_promote_unstable_el7.yaml
- rules/st2_pkg_test_and_promote_unstable_el8.yaml
- rules/st2_pkg_test_and_promote_unstable_u16.yaml
- rules/st2_pkg_test_and_promote_unstable_u18.yaml
Our stable daily builds tested ChatOps end-to-end, but our unstable builds did not. This PR simply sets that boolean parameter to `true` for the workflows.
> Test ChatOps end-to-end tests on daily CI builds

- actions/workflows/st2_pkg_e2e_test.yaml
This tiny PR simply updates the task that runs the ST2 bootstrap script to pass the `--u16-add-insecure-py3-ppa` flag. It does this during all OSes, since the OS detection logic is later in the workflow. The install script is smart enough to ignore unrecognized flags.
Closes #194.
> Use the --u16-add-insecure-py3-ppa flag

- rules/st2_pkg_e2e_test_centos7_on_st2_pr.yaml
- rules/st2_pkg_e2e_test_centos8_on_st2_pr.yaml
- rules/st2_pkg_e2e_test_ubuntu18_on_st2_pr.yaml
- rules/st2_pkg_e2e_test_ubuntu20_on_st2_pr.yaml
Disable the on-commit PR commit builds as they are currently having to be manually disabled whenever we do an update of the CI pack.
Given the desire to check on the AWS costings, suggest we disable them by default in the pack.
> Disable PR rules

- actions/st2_pkg_test_and_promote.meta.yaml
- actions/workflows/st2_pkg_test_and_promote.yaml
- rules/st2_pkg_test_and_promote_unstable_el7.yaml
Problems seen on the RHEL7 E2E builds with mirrors. As we want to move to CentOS7 anyway to reduce AWS costs, moved EL7 over to CentOS7 now.
> Move EL7 unstable to CentOS 7 to see if fix CI issues

- actions/README.md
- actions/st2_pkg_e2e_test.meta.yaml
- actions/st2_pkg_promote_all.meta.yaml
- actions/st2_pkg_test_and_promote.meta.yaml
- actions/st2_pkg_upgrade_e2e_test.meta.yaml
- actions/workflows/st2_pkg_e2e_test.yaml
- actions/workflows/st2_pkg_promote_all.yaml
- actions/workflows/st2_pkg_test_and_promote.yaml
- actions/workflows/st2_pkg_upgrade_e2e_test.yaml
- rules/st2_pkg_test_and_promote_unstable_el8.yaml
Use ROCKY8 instead of RHEL8 for E2E and upgrade workflows
Introduce windows_instance_type parameter so can use different size of windows instance type to ST2
Default windows instance type to t2.medium as starting point
> Introduce windows_instance_type parameter and use ROCKY8 for e2e tests
