actions/workflows/mistral.yaml, actions/workflows/setup_st2.yaml
Task result is not referenced using the task function in mistral workflows.
=> Fix references to task result in mistral workflows

actions/workflows/build_pkgs.yaml, actions/workflows/mistral.yaml, actions/workflows/st2_pkg_e2e_test.yaml, actions/workflows/st2_pkg_test_promote.yaml
=> Add fallback value to all atachments

rules/st2_pkg_test_unstable_u14.yaml
=> build parameters handling

actions/workflows/build_pkgs.yaml
Ended up with a strange error 
```
Exception: Failed to perform action chat.postMessage: {"ok":false,"error":"no_text"}
```
=> add missing "

actions/workflows/build_pkgs.yaml, actions/workflows/mistral.yaml, actions/workflows/st2_pkg_e2e_test.yaml, actions/workflows/st2_pkg_promote_all.yaml, actions/workflows/st2_pkg_test_and_promote.yaml, actions/workflows/st2_pkg_test_and_promote_enterprise.yaml, actions/workflows/st2_pkg_upgrade_e2e_test.yaml
We have no way of retrieving the hostname programmatically anymore so I am hardcoding it.
=> Updating build url

actions/workflows/st2_pkg_promote_enterprise.yaml
=> Fix action call - action only takes repo param

pack.yaml
See https://github.com/StackStorm/st2cd/pull/216
=> Change version to semver format

actions/bwc_pkg_promote_all.meta.yaml, actions/st2_pkg_e2e_test.meta.yaml, actions/st2_pkg_promote_all.meta.yaml, actions/st2_pkg_test_and_promote.meta.yaml, actions/st2_pkg_test_and_promote_enterprise.meta.yaml, actions/st2_pkg_upgrade_e2e_test.meta.yaml, actions/workflows/bwc_pkg_promote_all.yaml, actions/workflows/promote_package.yaml, actions/workflows/st2_pkg_promote_all.yaml, actions/workflows/st2_pkg_test_and_promote.yaml, actions/workflows/st2_pkg_test_and_promote_enterprise.yaml, actions/workflows/st2_pkg_upgrade_e2e_test.yaml, rules/st2_pkg_test_and_promote_unstable_u16.yaml, rules/st2_pkg_test_unstable_u16.yaml, rules/st2_pkg_test_unstable_u16_enterprise.yaml
arekhi@st2-build-node-1:~$ st2 key list | grep UBUNTU16
| ami_UBUNTU16                         | ami-746aba14                         | False  | False     | system |      |                  |
=> Support for Ubuntu 16 (Xenial)

actions/workflows/bwc_pkg_promote_all.yaml
=> Cleanup bwc_pkg_promote_all.yaml

actions/promote_package.yaml, actions/st2_pkg_promote.yaml, actions/st2_pkg_promote_enterprise.yaml, actions/workflows/bwc_pkg_promote_all.yaml, actions/workflows/st2_pkg_promote_all.yaml, actions/workflows/st2_pkg_test_and_promote_enterprise.yaml, rules/st2_pkg_test_unstable_u14_enterprise.yaml, rules/st2_pkg_test_unstable_u14_enterprise_dev.yaml, rules/st2_pkg_test_unstable_u14_enterprise_packaging.yaml, rules/st2_pkg_test_unstable_u16_enterprise.yaml, rules/st2_pkg_test_unstable_u16_enterprise_dev.yaml, rules/st2_pkg_test_unstable_u16_enterprise_packaging.yaml
=> Moving to st2kv

actions/workflows/build_pkgs.yaml, actions/workflows/build_pkgs_done.yaml, actions/workflows/bwc_pkg_promote_all.yaml, actions/workflows/mistral.yaml, actions/workflows/st2_pkg_e2e_test.yaml, actions/workflows/st2_pkg_promote_all.yaml, actions/workflows/st2_pkg_test_and_promote.yaml, actions/workflows/st2_pkg_test_and_promote_enterprise.yaml, actions/workflows/st2_pkg_upgrade_e2e_test.yaml
=> Moving st2-build references to st2cicd

actions/st2_pkg_e2e_test.meta.yaml, actions/st2_pkg_upgrade_e2e_test.meta.yaml
=> Use cpu-optimized instance for e2e_test

actions/workflows/mistral.yaml
Use updated https://github.com/StackStorm/mistral_dev pack, extracted from https://github.com/StackStorm/st2incubator/tree/master/packs/mistral-dev
=> Use new mistral_dev pack

actions/st2_docker_dev.yaml, actions/workflows/st2_docker_dev.yaml, rules/st2_docker_dev_rule.yaml
Similar to adding the following curl to a cron job:
```
curl --header "Content-Type: application/json" --data '{"build_parameters": {"BUILD_DEV": "true"}}' --request POST https://circleci.com/api/v1.1/project/github/StackStorm/st2-docker/tree/feature/circleci?circle-token=$CIRCLE_TOKEN
```
With the advantage of adding notification via slack on success/failure.
=> Initial draft of docker dev build

actions/promote_package.yaml, actions/workflows/promote_package.yaml, aliases/promote_package.yaml
Work on https://github.com/StackStorm/st2-packages/issues/365 to remove Debian `Wheezy` and `Jessie`.
=> Remove Debian Wheezy & Jessie

actions/workflows/build_pkgs.yaml
Adding required `username` input field.
=> Add username

actions/workflows/st2_pkg_upgrade_deb.yaml, actions/workflows/st2_pkg_upgrade_rpm.yaml
Add step to upgrade nodejs to >= 6.x in the package upgrade workflows.
=> Add step to upgrade nodejs in the package upgrade workflows

actions/st2_pkg_upgrade_deb.meta.yaml, actions/st2_pkg_upgrade_deps_el6.meta.yaml, actions/st2_pkg_upgrade_deps_el6.sh, actions/st2_pkg_upgrade_deps_el7.meta.yaml, actions/st2_pkg_upgrade_deps_el7.sh, actions/st2_pkg_upgrade_deps_u14.meta.yaml, actions/st2_pkg_upgrade_deps_u14.sh, actions/st2_pkg_upgrade_deps_u16.meta.yaml, actions/st2_pkg_upgrade_deps_u16.sh, actions/st2_pkg_upgrade_rpm.meta.yaml, actions/workflows/st2_pkg_upgrade_deb.yaml, actions/workflows/st2_pkg_upgrade_e2e_test.yaml, actions/workflows/st2_pkg_upgrade_rpm.yaml
Refactor the upgrade workflow to abstract the handling of dependencies upgrade specific to distro and st2 version. Each distro will have a separate upgrade script. The script itself will contain the commands for handling the dependency upgrade if needed.
=> Refactor the upgrade workflow to abstract the handling of dependencies upgrade

actions/workflows/st2_pkg_e2e_test.yaml
Pseudocode:
```
if initial_commit != null:
set_github_status_pending
on_success
create_vm
else:
create_vm
```
=> Modify st2_pkg_e2e_test w/f based on initial_commit value

actions/bwc_pkg_promote_all.meta.yaml, actions/st2_pkg_e2e_test.meta.yaml, actions/st2_pkg_promote_all.meta.yaml, actions/st2_pkg_test_and_promote.meta.yaml, actions/st2_pkg_test_and_promote_enterprise.meta.yaml, actions/st2_pkg_upgrade_deb.meta.yaml, actions/st2_pkg_upgrade_e2e_test.meta.yaml, actions/workflows/bwc_pkg_promote_all.yaml, actions/workflows/st2_pkg_promote_all.yaml, actions/workflows/st2_pkg_test_and_promote.yaml, actions/workflows/st2_pkg_upgrade_deb.yaml, actions/workflows/st2_pkg_upgrade_e2e_test.yaml, rules/st2_pkg_e2e_test_ubuntu18_on_st2_pr.yaml, rules/st2_pkg_test_and_promote_unstable_u18.yaml, rules/st2_pkg_test_and_promote_unstable_u18_enterprise.yaml, rules/st2_pkg_test_unstable_u18.yaml, rules/st2_pkg_test_unstable_u18_dev.yaml, rules/st2_pkg_test_unstable_u18_enterprise.yaml, rules/st2_pkg_test_unstable_u18_enterprise_dev.yaml, rules/st2_pkg_test_unstable_u18_enterprise_packaging.yaml, rules/st2_pkg_test_unstable_u18_packaging.yaml
This pull request updates various rules and actions and adds support for Ubuntu Bionic.
=> Add support for Ubuntu Bionic

actions/st2_pkg_upgrade_deps_el6.sh, actions/st2_pkg_upgrade_deps_el7.sh
=> Use sudo when running sed

actions/st2_pkg_upgrade_deps_u18.meta.yaml, actions/st2_pkg_upgrade_deps_u18.sh
This pull request adds missing ``st2ci.st2_pkg_upgrade_deps_u18 action`` action
=> Add missing st2_pkg_upgrade_deps_u18 action

actions/workflows/st2_pkg_e2e_test.yaml
Same root cause as #127.
Avoids triggering Orquesta #112.
=> Refactor cleanup logic to be sequential

actions/workflows/st2_pkg_e2e_test.yaml
Fix formatting of YAQL expression and remove duplicate dashes from the bootstrap script arg.
=> More runtime related fixes

actions/mistral.yaml, actions/setup_st2.yaml, actions/workflows/mistral.yaml, actions/workflows/mistral_get_build_hosts.yaml, actions/workflows/mistral_get_commit_shas.yaml, actions/workflows/mistral_setup_infra.yaml, actions/workflows/setup_st2.yaml
This PR likely needs more work, but so far it has the `st2ci.mistral` workflow (and subworkflows) working and passing.
=> Fix point release workflows

actions/workflows/bwc_pkg_promote_all.yaml, actions/workflows/st2_pkg_upgrade_e2e_test.yaml
This pull request updates enterprise release workflows to take into account and promote new ``st2-rbac-backend`` package.
=> Update release workflows to take into account new st2-rbac-backend package

actions/st2_pkg_e2e_test.meta.yaml, actions/workflows/st2_pkg_e2e_test.yaml
This has been running on st2cicd for awhile. It's time to merge it in!
=> Add a chatops flag

actions/bwc_pkg_promote_all.meta.yaml, actions/st2_pkg_promote_all.meta.yaml, actions/workflows/st2_pkg_promote_all.yaml
Uncomment bionic packages from promotion. Remove st2flow from the st2_pkg_promote_all.
=> Clean up st2_pkg_promote_all workflow

actions/workflows/st2_pkg_promote_all.yaml
Refactor the logic that determines success and failure to exclude st2mistral for bionic.
=> Remove mistral for bionic when determining success

actions/bwc_pkg_promote_all.meta.yaml, actions/st2_pkg_e2e_test.meta.yaml, actions/st2_pkg_promote_all.meta.yaml, actions/st2_pkg_test_and_promote.meta.yaml, actions/st2_pkg_test_and_promote_enterprise.meta.yaml, actions/st2_pkg_upgrade_deps_el8.meta.yaml, actions/st2_pkg_upgrade_deps_el8.sh, actions/st2_pkg_upgrade_e2e_test.meta.yaml, actions/st2_pkg_upgrade_rpm.meta.yaml, actions/workflows/bwc_pkg_promote_all.yaml, actions/workflows/st2_pkg_promote_all.yaml, actions/workflows/st2_pkg_test_and_promote.yaml, actions/workflows/st2_pkg_upgrade_rpm.yaml, aliases/promote_package.yaml, rules/st2_pkg_e2e_test_centos8_on_st2_pr.yaml, rules/st2_pkg_test_and_promote_unstable_el8.yaml, rules/st2_pkg_test_and_promote_unstable_el8_enterprise.yaml
=> initial st2ci changes for EL8

actions/run_all_nightlies.meta.yaml, actions/workflows/run_all_nightlies.yaml
=> Add workflows to run all nightly workflows

actions/run_all_nightlies.meta.yaml, actions/workflows/run_all_nightlies.yaml
Fix syntax for `run_all_nightlies` workflow.
=> Fix enterprise_keys reference syntax

actions/cleanup_diskspace.sh, actions/cleanup_diskspace.yaml, actions/workflows/st2_pkg_e2e_test.yaml
Add a step after requirements are installed to clear disk space on the system.
=> Add step to clear some diskspace before proceeding with tests

actions/workflows/st2_pkg_e2e_test.yaml
Add hosts and timeout to the workflow step
=> Fix workflow step to cleanup diskspace

actions/workflows/st2_pkg_upgrade_e2e_test.yaml
Based on suggestion from @blag added explicit check for each OS by an equality check with its full name.
=> Added explicit check for all OSes

actions/workflows/install_latest_revision_of_rpm_pkg.yaml
=> add yum update timeout to 5 min

actions/workflows/st2_pkg_upgrade_e2e_test.yaml
I had the Ubuntu tests in the RPM path and the RHEL tests in the DEB path. Sorry!
=> Fixing upgrade e2e tests to verify distro in proper branch

actions/install_latest_revision_of_rpm_pkg.meta.yaml, actions/st2_pkg_e2e_test.meta.yaml, actions/st2_pkg_upgrade_e2e_test.meta.yaml, actions/st2_pkg_upgrade_rpm.meta.yaml, actions/workflows/install_latest_revision_of_rpm_pkg.yaml, actions/workflows/st2_pkg_upgrade_e2e_test.yaml, actions/workflows/st2_pkg_upgrade_rpm.yaml, rules/st2_pkg_e2e_test_rocky8_on_st2_pr.yaml
Move any CentOS8 runs to Rocky8
Part of https://github.com/StackStorm/community/issues/88
=> Rocky changes
